### ISSUE TITLE
Before announcing

### ISSUE THREAD

**Issue by SilverRainZ** [SrainApp/srain#66]
- [x] 保留头像功能，~~整理其 python 接口的代码~~ / 或者砍掉
- [x] Libsoup 代替 cURL，使图片预览真正可用
- [x] CTCP 实现 #65 
- [x] CAP 实现 #74 
- [x] SASL 支持 #68 
- [x] 和系统主题能和谐存在的主题 / 有可能的话做一个独立主题 #81 
- [x] Decorator 和 filter 支持处理 XML
- ~~Decorator 插件接口[DELAY]~~ #130
- ~~libpesa 插件引擎 [DELAY]~~ #79 
- ~~005 消息的支持及相关工作 [DELAY]~~
- [x] IRC 颜色支持 #31 
- [x] 支持连接预定义服务器的连接面面板 #70 
- [x] 支持搜索频道的 JOIN 面板，即实现 /list #70 
- [x] 支持通过 `irc://xxx` 形式的 URL 连接服务器和加入频道
- [x] 改善用户过多时 SrainChat 的释放速度 #70
- ~~提高消息积累过多时程序的 FPS [DELAY]~~
- [x] Input entry 支持多行输入 #51 
- [x] Input entry 支持历史记录 #51 
- ~~自定义快捷键支持 #118 [DELAY]~~
- [x] 更好的补全（nick 和 命令） #51
- [x] 有继承关系的 SrainChat(SrainBuffer) #73
- [x] 完备的连接控制：连接状态机 #77
- [x] 整理配置文件 #93 
- [x] 全局的 Application 对象，整理启动流程 #93
- [x] 让 Server 对象持有 User 
- [x] 新版 UI #81 
- [x] 假的配置面板 #121

感觉能在 18 年末做完就不错了。

**Comment by yinflying** [comment]
慢慢做呗。

**Comment by SilverRainZ** [comment]
Due to the limited time, the features marked as `[DELAY]` will not appear in release `1.0`.

**Comment by SilverRainZ** [comment]
:tada: :tada: :tada:

**Comment by VOID001** [comment]
:tada: :tada: :tada:
